name: RuneForgedRunes
version: 1.0
main: me.gauravbuilds.runeforgedrunes.RuneForgedRunes
api-version: 1.21
authors: [GauravBuilds]
description: A high-performance Rune system plugin where players apply custom runes to items for permanent buffs using drag-and-drop mechanics.
softdepend: [Vault, PlaceholderAPI]
permissions:
  runeforged.admin:
    description: Allows taking runes from GUI and using admin commands.
    default: op

commands:
  runes:
    description: Opens the Rune Repository
    usage: /runes [subcommand]
    aliases: [rune]